// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWCyZXW_B41MZBJzeuII6c6raL7PCJ0I',
    appId: '1:97893654048:web:eaf2618e4518cfcc88e645',
    messagingSenderId: '97893654048',
    projectId: 'pushnotification-fe894',
    authDomain: 'pushnotification-fe894.firebaseapp.com',
    storageBucket: 'pushnotification-fe894.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQC0O59q2krbB8ikMQntSPq9xwWXi06Sw',
    appId: '1:97893654048:android:630f88208ad5403188e645',
    messagingSenderId: '97893654048',
    projectId: 'pushnotification-fe894',
    storageBucket: 'pushnotification-fe894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwPKfl3Ay_GBZGIy-zd95wnN0n770haRw',
    appId: '1:97893654048:ios:be2114dd69353a5c88e645',
    messagingSenderId: '97893654048',
    projectId: 'pushnotification-fe894',
    storageBucket: 'pushnotification-fe894.firebasestorage.app',
    iosBundleId: 'com.example.buildApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwPKfl3Ay_GBZGIy-zd95wnN0n770haRw',
    appId: '1:97893654048:ios:be2114dd69353a5c88e645',
    messagingSenderId: '97893654048',
    projectId: 'pushnotification-fe894',
    storageBucket: 'pushnotification-fe894.firebasestorage.app',
    iosBundleId: 'com.example.buildApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZWCyZXW_B41MZBJzeuII6c6raL7PCJ0I',
    appId: '1:97893654048:web:9b1ba80ee75a941288e645',
    messagingSenderId: '97893654048',
    projectId: 'pushnotification-fe894',
    authDomain: 'pushnotification-fe894.firebaseapp.com',
    storageBucket: 'pushnotification-fe894.firebasestorage.app',
  );
}
